# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

# dump_dir: !!CHANGETHIS!!
dump_dir: /tmp/debug_modular_dump
name: "debug_modular"
steps: 1000
probe_freq: 100
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    fsdp_type: full_shard
    compile: false
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 1024
    n_layers: 8
    n_heads: 8
    module_seq_len : 1024
    module_agg: "avg"  # can be: sum, mean, stack or drop
    create_module_name : None # set this to the name of the module you want to create

data:
    root_dir: /datasets/shared_datasets/fineweb/
    sources:
        fineweb_edu_10bt_shuffled: 1.0
    batch_size: 8
    prefetch_size: 64
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        path: /local_data/tokenizers/original/tokenizer.model
        name: bytes

profiling:
    run: true

checkpoint:
    dump:
        every: 100
        keep: 1
    eval:
        every: 100
        keep: 1

logging:
    freq: 10

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - hellaswag
            - piqa
            - task: nq_open
              num_fewshot: 5
    validation:
        max_steps: 100
